### ISSUE TITLE
Preview is not working

### ISSUE THREAD

**Issue by mknyein** [rderoldan1/md_simple_editor#2]
When I click preview button, it is not working. Aslo, table and some tag is not working.

**Comment by rderoldan1** [comment]
Do you see an error in your developer tools, or in server's log ?

**Comment by retronoodle** [comment]
Hi this is a really great Gem! Would it be possible to get a quick example of how to override the button styles? I just want to make them extra small. Thanks!

**Comment by rohan-panchal** [comment]
I'm seeing this as well. I'm using this in a rails 5 scaffolded model.

I put 

```
  <div class="field">
    <%= md_simple_editor do %>
        <%= f.text_area :content %>
    <% end %>
  </div>
```

In the _form.

And the problem happens when i traverse to `edit`.

Upon first load of the page preview/none of the buttons work from the md_simple_editor toolbar.

If i refresh the page it then works.

**Comment by BScharbau** [comment]
Had the same error, console gave me the error
`NameError (uninitialized constant MdSimpleEditorController::Redcarpet)`
Seems like `md_simple_editor` does not automatically install all of it's dependencies with `bundle install`.
Fixed it by adding `gem 'redcarpet'` in my Gemfile and running `bundle install`. Not sure if it's the same issue for you, but you might give it a try

**Comment by rohan-panchal** [comment]
I didn't run into that specific issue.

I had redcarpet already declared in my gemfile when i ran into this issue.

**Comment by rderoldan1** [comment]
I released a new version `0.3.0` please give a try. I tested in a new rails app and it worked. 

I request @mk-nyein for details, I don't have more info, so I'm going to close this issue

**Comment by BScharbau** [comment]
I did some further research into that. It seems that activating `turbolinks` in your project (which is the default with Rails 5, not sure about older versions), there seem to be soome issues when loading javascript and not making sure they are loaded after turbolinks finished setting things up.

I run a fork of md_editor, because I wanted to replace the preview window by a live preview, and I had to include a line

    $(document).on 'turbolinks:load', ->

in my javascript assets to make sure it runs on page load.

**Comment by mknyein** [comment]
It works on both chrome and firefox. Thanks.

**Comment by arrowak** [comment]
In my case it was csrf_token invalid issue (look in your server-side error logs). If you are on rails and have the same issue, then in your application.js file add following code - 

```
$(document).on('ready turbolinks:load page:load', function () {
    $.ajaxSetup({
        headers:
            { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
    });
});
```

The issue should now be resolved.
