### ISSUE TITLE
Override button style

### ISSUE THREAD

**Issue by retronoodle** [rderoldan1/md_simple_editor#3]
Hi this is a really great Gem! Would it be possible to get a quick example of how to override the button styles? I just want to make them extra small. Thanks!

**Comment by rderoldan1** [comment]
do you want to change the classes?

**Comment by retronoodle** [comment]
I would like to make the buttons sm or xs (smaller buttons) 

Thanks!

**Comment by rderoldan1** [comment]
Hi, I added a new version, now you can add additional classes, like the button size
```ruby
  <%= md_simple_editor('btn-xs')  do %>
      <%= text_area_tag "your id", '', class: 'form-control' %>
  <% end %>
```

![screen shot 2017-03-09 at 10 59 33 am](https://cloud.githubusercontent.com/assets/968973/23758367/881983e0-04b7-11e7-94ef-04d492b3b6ff.png)
![screen shot 2017-03-09 at 11 00 11 am](https://cloud.githubusercontent.com/assets/968973/23758400/a690c0fe-04b7-11e7-99e5-9ce54844e556.png)
![screen shot 2017-03-09 at 11 00 27 am](https://cloud.githubusercontent.com/assets/968973/23758401/a6ab13dc-04b7-11e7-99de-fb208b1bd61c.png)

**Comment by retronoodle** [comment]
Thank you! Thats awesome.
