### ISSUE TITLE
Preview button doesn't work (422 (Unprocessable Entity)) error

### ISSUE THREAD

**Issue by JimmyW17** [rderoldan1/md_simple_editor#7]
Clicking the preview button doesn't do anything and gives the 422 (Unprocessable Entity) error on console. I've tried the solutions on the previous issue, but those didn't help. And it's a different error message than the other issue report.

**Comment by JimmyW17** [comment]
Forgot to mention, I tried using it on a rails app.

<%= md_simple_editor  do %>
        <%= f.text_field :title, :placeholder => 'Title'%><br><br>
        <%= f.text_area :content, :rows => 20, :cols => 150 %>
    <% end %>

**Comment by rderoldan1** [comment]
Hi @JimmyW17 could you add your gem version, also what is in your rails log and web inspector console?

**Comment by JimmyW17** [comment]
Sure.
md_simple_editor-0.3.0

Web inspector console : 
POST http://localhost:3000/md_simple_editor/preview 422 (Unprocessable Entity)
send @ jquery-3.2.1.min.js:4
ajax @ jquery-3.2.1.min.js:4
r.(anonymous function) @ jquery-3.2.1.min.js:4
preview @ md_simple_editor.self-d201807….js?body=1:28
(anonymous) @ md_simple_editor.self-d201807….js?body=1:78
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3

How do I get the rails log?

**Comment by JimmyW17** [comment]
I fixed it. I commented out my jquery cdn link tag and it works.
